# Tasks for Debian Based Routers

- name: Install packages from APT
  apt:
    name: ["nftables", "tcpdump"]
  become: yes

- name: Enable IP forwarding
  sysctl:
    name: "{{item}}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Update Firewall config
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify:
    - reload firewall
  become: yes
